---
services:
  samba:
    container_name: samba
    image: cdzombak/samba-docker:4.19.3
    hostname: mynas
    network_mode: host
    restart: always
    ulimits:
      nofile:
        soft: 16384
        hard: 32768
    volumes:
      - /home/mysystemuser:/home/mysystemuser
      - /mnt/storage:/mnt/storage
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - /etc/group:/etc/group:ro
      - ./10-tz.sh:/etc/cont-init.d/10-tz.sh:ro
      - ./70-smbusers.sh:/etc/cont-init.d/70-smbusers.sh:ro
      - ./smb.conf:/usr/local/samba/etc/smb.conf:ro
      - /var/log/samba-docker:/usr/local/samba/var/log
